import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  
  header: {
    backgroundColor: '#5d873e',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    alignItems: 'center',
  },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#fff' },
  
  // TABS
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e8e8e8',
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: '#5d873e',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#999',
  },
  tabTextActive: {
    color: '#5d873e',
  },
  tabTextArchived: {
    color: '#ff9800',
  },
  
  // MAIN CONTENT - Centered
  mainContent: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  
  centerColumn: {
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
    padding: 16,
  },
  
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: '#333' },
  
  categoriesRow: { 
    marginBottom: 16,
    flexGrow: 0,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#fff',
    marginRight: 6,
    borderWidth: 1.5,
    borderColor: '#5d873e',
  },
  categoryButtonActive: { backgroundColor: '#5d873e', borderColor: '#5d873e' },
  categoryText: { fontSize: 12, fontWeight: '600', color: '#5d873e', marginLeft: 4 },
  categoryTextActive: { color: '#fff' },
  
  createPostToggle: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#5d873e',
  },
  createPostToggleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  createPostPlaceholder: {
    fontSize: 14,
    color: '#5d873e',
    fontWeight: '600',
    marginLeft: 8,
  },
  
  createPostForm: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#5d873e',
  },
  createPostHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  createPostHeaderText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#5d873e',
  },
  postTitleInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  postCategoryRow: { 
    marginBottom: 8,
    flexGrow: 0,
  },
  postCategoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: '#f5f5f5',
    borderWidth: 1.5,
    borderColor: '#5d873e',
    marginRight: 6,
  },
  postCategoryChipActive: { backgroundColor: '#5d873e' },
  postCategoryChipText: { fontSize: 11, fontWeight: '600', color: '#5d873e', marginLeft: 3 },
  postCategoryChipTextActive: { color: '#fff' },
  postContentInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: '#333',
    minHeight: 80,
    lineHeight: 18,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  postErrorText: {
    color: '#c33',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 8,
    marginLeft: 4,
  },
  
  // Multiple Images Support
  imagePreviewsContainer: {
    marginBottom: 8,
    flexGrow: 0,
  },
  imagePreviewWrapper: {
    position: 'relative',
    marginRight: 8,
  },
  imagePreviewSmall: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  imageRemoveButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#fff',
    borderRadius: 11,
  },
  postActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  addPhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    borderWidth: 1.5,
    borderColor: '#5d873e',
    gap: 4,
  },
  addPhotoText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#5d873e',
  },
  postSubmitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5d873e',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 16,
  },
  postSubmitButtonDisabled: { opacity: 0.6 },
  postSubmitText: { color: '#fff', fontSize: 13, fontWeight: '600', marginLeft: 6 },
  
  postsContainer: { marginTop: 4 },
  postCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  postHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e8f5e9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#5d873e',
    overflow: 'hidden',
  },
  userAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  userInfo: { marginLeft: 10, flex: 1 },
  username: { fontSize: 13, fontWeight: '600', color: '#5d873e', marginBottom: 2 },
  timeContainer: { flexDirection: 'row', alignItems: 'center' },
  timeAgo: { fontSize: 11, color: '#666' },
  editedBadge: { fontSize: 10, color: '#999', marginLeft: 4, fontStyle: 'italic' },
  postActionsIcons: { flexDirection: 'row', gap: 6 },
  iconButton: { padding: 4 },
  postContent: { marginBottom: 8 },
  postTitle: { fontSize: 15, fontWeight: 'bold', color: '#2d3e2d', marginBottom: 6 },
  
  // Multiple Images in Post Display
  imagesContainer: {
    marginBottom: 6,
    flexGrow: 0,
  },
  postCardImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
  },
  postCardImageMultiple: {
    width: 200,
    marginRight: 8,
  },
  
  postText: { fontSize: 13, color: '#555', lineHeight: 18 },
  postFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e8e8e8',
  },
  actionItem: { flexDirection: 'row', alignItems: 'center', marginRight: 16 },
  actionText: { fontSize: 12, color: '#5d873e', fontWeight: '600', marginLeft: 5 },
  disabledIcon: { opacity: 0.5 },
  disabledText: { opacity: 0.5 },
  emptyText: { textAlign: 'center', color: '#999', marginTop: 30, fontSize: 14 },
  
  unarchiveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5d873e',
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: -8,
    marginBottom: 12,
  },
  unarchiveButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 6,
  },
  
  loginPrompt: {
    backgroundColor: '#fff',
    marginTop: 16,
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  loginPromptText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 14,
    lineHeight: 20,
  },
  loginPromptButton: {
    backgroundColor: '#5d873e',
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 18,
  },
  loginPromptButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  chatbotButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#5d873e',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  chatbotBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#5d873e',
  },
  // MODAL STYLES
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2d3e2d',
    marginTop: 12,
  },
  modalMessage: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 22,
  },
  modalWarning: {
    fontSize: 14,
    color: '#ff9800',
    textAlign: 'center',
    marginBottom: 24,
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#f5f5f5',
    borderWidth: 2,
    borderColor: '#5d873e',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#5d873e',
  },
  archiveButton: {
    backgroundColor: '#ff9800',
  },
  archiveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
});