import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },

  header: {
    backgroundColor: '#5d873e',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
  },
  backButton: { padding: 4 },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: 'bold', color: '#fff', textAlign: 'center' },
  headerActions: { flexDirection: 'row', gap: 8 },
  headerButton: { padding: 4 },

  scrollView: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
  },

  authorRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e8f5e9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#5d873e',
    marginRight: 10,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  authorName: { fontSize: 15, fontWeight: '600', color: '#5d873e' },
  timeContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  authorTime: { fontSize: 12, color: '#888' },
  editedBadge: { fontSize: 11, color: '#999', marginLeft: 4, fontStyle: 'italic' },
  categoryBadge: {
    marginLeft: 'auto',
    backgroundColor: '#e8f5e9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#5d873e',
  },
  categoryBadgeText: { fontSize: 12, fontWeight: '600', color: '#5d873e' },

  imageScrollContainer: { marginBottom: 16 },
  imageScrollContent: { paddingRight: 20 },
  postImage: {
    width: 300,
    height: 220,
    borderRadius: 12,
    objectFit: 'cover',
  },
  postContent: { fontSize: 15, color: '#444', lineHeight: 22, marginBottom: 20 },
  likeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  likeText: { fontSize: 15, color: '#5d873e', fontWeight: '600', marginLeft: 8 },
  likeTextActive: { color: '#e74c3c' },
  disabledIcon: { opacity: 0.5 },
  disabledText: { opacity: 0.5 },

  divider: { height: 1, backgroundColor: '#e8e8e8', marginBottom: 20 },

  commentsHeading: { fontSize: 17, fontWeight: 'bold', color: '#2d3e2d', marginBottom: 12 },
  noComments: { fontSize: 14, color: '#999', textAlign: 'center', marginVertical: 16 },

  commentCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  commentHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  commentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e8f5e9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  commentAuthor: { fontSize: 13, fontWeight: '600', color: '#5d873e', marginRight: 6 },
  commentTime: { fontSize: 11, color: '#999', flex: 1 },
  commentActions: { flexDirection: 'row', gap: 6 },
  commentActionButton: { padding: 2 },
  commentBody: { fontSize: 14, color: '#555', lineHeight: 20 },

  replyBadgeContainer: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4 },
  replyBadgeText: { fontSize: 11, color: '#5d873e', fontStyle: 'italic' },

  commentActionBar: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 8 },
  commentLikeButton: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  commentLikeText: { fontSize: 12, color: '#5d873e', fontWeight: '600' },
  commentLikeTextActive: { color: '#e74c3c' },
  commentReplyButton: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  commentReplyText: { fontSize: 12, color: '#5d873e', fontWeight: '600' },

  editCommentInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#333',
    borderWidth: 1,
    borderColor: '#5d873e',
    marginBottom: 8,
    minHeight: 60,
  },
  editActions: { flexDirection: 'row', gap: 8 },
  saveButton: {
    backgroundColor: '#5d873e',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
  },
  saveButtonText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  cancelEditButton: {
    backgroundColor: '#e8e8e8',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
  },
  cancelEditButtonText: { color: '#666', fontSize: 13, fontWeight: '600' },

  loginPrompt: {
    backgroundColor: '#fff',
    marginTop: 16,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#5d873e',
  },
  loginPromptText: {
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 16,
    lineHeight: 22,
  },
  loginPromptButton: {
    backgroundColor: '#5d873e',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 25,
  },
  loginPromptButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },

  commentInputContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e8e8e8',
    alignItems: 'center',
  },
  commentInputWrapper: {
    maxWidth: 600,
    width: '100%',
  },
  replyIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#e8f5e9',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  replyIndicatorText: { fontSize: 12, color: '#5d873e', flex: 1 },
  commentInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  commentInput: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    color: '#333',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    marginRight: 10,
    maxHeight: 100,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#5d873e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonDisabled: { opacity: 0.4 },
  commentErrorText: {
    color: '#ff3b30',
    fontSize: 11,
    marginTop: 4,
    marginLeft: 2,
  },
});
